spring.application.name=CloudShare-Test

# AWS Credentials & Region
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test


S3_UPLOAD_BUCKET_NAME=test-bucket-name

# Cognito
aws.cognito.client-id=test-client-id
COGNITO_USERPOOL_ID=test-pool-id
COGNITO_ISSUER_URI=https://cognito-idp.eu-central-1.amazonaws.com/test-pool

logging.level.root=INFO
logging.level.com.example.demo=DEBUG